name: ar_app
description: "An AR Hoang Thanh Thang Long project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.3
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  dots_indicator: ^3.0.0
  # flutter_unity_widget: ^2022.2.1
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/intro.jpg
    - assets/image/Home1/1.png
    - assets/image/Home1/2.png
    - assets/image/Home1/3.jpg
    - assets/image/Home1/4.png
    - assets/image/Home1/6.jpg
    - assets/image/Home1/5.jpg
    - assets/image/Home1/7.jpg
    - assets/image/CotCo/CotCoHN1.jpg
    - assets/image/CotCo/CotCoHN2.jpg
    - assets/image/CotCo/CotCoHN3.jpg
    - assets/image/DoanMon/1.jpg
    - assets/image/DoanMon/2.jpg
    - assets/image/DoanMon/3.jpg
    - assets/image/DoanMon/4.jpg
    - assets/image/HauLau/1.jpg
    - assets/image/HauLau/2.jpg
    - assets/image/HauLau/3.jpg
    - assets/image/BacMon/1.jpg
    - assets/image/BacMon/2.jpg
    - assets/image/BacMon/3.jpg
    - assets/image/BacMon/4.png
    - assets/image/D67/1.jpg
    - assets/image/D67/2.jpg
    - assets/image/D67/3.jpg
    - assets/image/D67/4.jpg
    - assets/image/KhaoCo/1.jpg
    - assets/image/KhaoCo/2.jpg
    - assets/image/KhaoCo/3.jpg
    - assets/image/KhaoCo/4.jpg
    - assets/image/KinhThien/1.jpg
    - assets/image/KinhThien/2.jpg
    - assets/image/KinhThien/3.jpg
    - assets/image/KinhThien/4.jpg
    - assets/image/logo.png
    - assets/image/Home/HTTL.jpg
    - assets/image/Home/news.jpg
    - assets/image/Home/tour.jpg
    - assets/image/Home/1.jpg
    - assets/image/Home/2.jpg
    - assets/image/Home/3.jpg
    - assets/image/Home/4.jpg
    - assets/image/Destination/cover_page.webp
    - assets/destination/BacMon.txt
    - assets/destination/CotCo.txt
    - assets/destination/D67.txt
    - assets/destination/DoanMon.txt
    - assets/destination/HauLau.txt
    - assets/destination/KhaoCo.txt
    - assets/destination/KinhThien.txt

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

